import { Inter } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.scss";
import theme from "@/config/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alphaspay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
