name: Deploy Next App
on:
  push:
    branches: [stagging]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    env:
      SSH_KEY: -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABDhVqozL/
        8KvPT78ymUqSv7AAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQCxj2eLBl9I
        s46EKBFVB0i1ls64Uab98ebFjKX9HYLTHVZ3cIGg91kXyux4i+Bfnbz/zgSymwa8BzI+Ic
        0vs/S8wH+eXLR3VEGUQf8IgvtTi4cqHFeQWoF0dHqcimn33cL1MvEiRSrC7DNBg+eznloY
        vFxnrrpFQMHgkCGT3ARndD8hOncWGXlGw03mjVjXpPf61e+S9qgBDm4Pk/Yj3DS9OezXgU
        5gqoTpKP64ZxuT1pggNDbSh87nuXE+gtMVsLAOUXbyoT0P6tPWb7JxHooffIxJqF15WfWs
        etdScJO5YtRQ1yYIkqZJUsCmzFh7OnZtsagexbT21Dh17XUQfhPQrVXG9i6daZMyFvEoxf
        KA9woBHVzvpoe3QnpyF+FLwRISRIZU9YnlSS/wGVFFGYLl/eeYpxXzDcjWT/rUp1QDlK9N
        0jI0z47EcYsqQv8px3WyJuWkvpjkF6omT0+zrt5nAcPYiLudlJs+SaTK1+ZA322Bo/XaD+
        qtyZemrM5FXxMAAAWQp3Xw0mYLF85R5Lw+KTwljqh3xHNFSKX9KYncz0Q4DixL8vNs+18k
        3fOiI+fNF2jguPYJuZFWNnJp3ahFFiIWJoHYeebEuH3KMa3Gc83rn0BdKr0RrM1LmisN66
        bipKJoV18Eh3MEiYvYStCKs7hf04iZ/Lt8S8crA6hZXajQ84psojRQzlHBD/xCExEUzwQO
        yriHTUaRQC5PssdgIRfcc8K/aR73Y3pKLDRc6CvUb7lkjgK9ONyFBAN+zfrJzMQGui3xN1
        /Uk9zfPu2l9sKp0CHJEbKAqWWJZrgK8raTRCQcwuD/HquZrf3XQb/RxuHFp5iDdMB68kO1
        VGFoh+u/LbqIfeyrhKt4oLKRgw+7LMN+iWV7H+CtigSzxdUOgok1wyoDJ+8e4pguHdCUwX
        dcVzoy5VrVeKMPhOa+QrzYdvSx0M1gr5Ug3lYgFwGrxdOzfDI/45TuVJF8wvg2iYmbMVxx
        0eUyx/Je4Ls8aSYklyDFCuRQe19iRy/Zpakwm+MiEGPGtU45ewz0TeJcN6KhD5b23aePry
        Z95aoTrTHzgE9XncYiAhxCmipJli35CGfC9rwFSQW9TRLTHw1w5wwx1ysuzQZMeASoNOMG
        AMWf1B/8JbLcRkkB0oqjnkeLUEsH9lmmlrCVk90ryIH/tIN9yOqB/bl5gwyE2Q0FdjkO4J
        3ESWvpUOk1aO1/+kbDvsLy27CrtVrYVrpAYwadlWWYNd0jfyCOvLLyBo9QNeu5gJByOA/8
        12SyGsKTfuvIZLTiGpZmBKg/7g79fmQ1EpcsbNEel3z+JoUH/GMjX1jEKhpHiBMlU2ubVQ
        z/+k8Ippf/q6KAurpxe7IJQnRgDrGuN83DvLdXZukfkEJXV36H5Rxr8ElTZdhmphK0rfar
        heOrBaFoaTbg1zxkdHm02NilqlrPcaMrdPe0tXn2AdJ8gVoCZkpE6TtFrv1Xf6BnXcy/oz
        dROsMZKqBNo4xScY+4Yb8B3nlZs4ZqIY4n9qtH+zOV7HkqeaVNlZoChUmMSIoN6w56H+fM
        f97pO9xyynN7zPvTqOIAMsM5dQcbA0EohIx0+EcvJTA//v0ma8R9DOOAi9EGlmk4Y5XTTD
        9jFPj2Y3ibRX4Rr5dc2p4YmwEp/Z0l0r+dgbNXGmb+e8+OEOIhAQ9FufQFYcQTVuRPdRgj
        UXBMc6rvNevqYuKIsXJbDLNXE/R9fwjNCJ1RRmVWLhsYDq3el+L2BPuIvIEXxFuOi4LXZU
        +/JzbZ9ZErncc202ahcmtEH81ue5eRQAeerV/mJC9TfEemQ5PTOG30W9icvOw62pYwpwTX
        5VnA3ch/Vvr4rK/I6cDSxIqSigFuiv/u6VsbpwAXZC6Eq1v6vYqtuvB64Q1MVvCPnyXrWw
        E5vzkW6a5WUrfDkaD/Nx2/fwEmU8aeF4qPC82KQUZ2kwVGG8nkqDP5XyXIQSIPH9sCuUwx
        oZ6kSJKi8oFeCs+iQcsL/Qp1AMnNltLF/x6ZYvadIWot1ya/WK0z68y4Fk6BOXaeTikEQM
        mlfUQf+QvgLJFU04Q+77Fk0Vc/Bf5dY27I1J9TgOHKYfh+aJzHSxnvxkw7YkWDEnIBKfx4
        jPkaa0Mvv7Qftm1sWttBiQEWHvu63dHXpjRBA9QapwplgyNlnoOYFhQoYQKG8mEmHTiDxv
        yXF1UyO+ZWjs6vQobKt73eVLQIbnJbpD5YlhLm8ipltQwXJfe1xmB/pGZt2W3vByNBc6Lh
        JP4+ZVR2OTgb0UTh2tuNDFIzsn/nOi9/nUkKStuVLIVadbsY9NUdV5gFScawoBz2IMZhcU
        wkcgXDJFQmKDSQL986TC7TyyFpN53qS0q/lv1MgVPKXJixDewzxTXXk+Rsqq1WorrYfSgW
        r9WtrYEecbo2nbPY0uv/zh22bY8=
        -----END OPENSSH PRIVATE KEY-----
        
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build
      - run: mkdir ~/.ssh
      - run: echo "$SSH_KEY" >> ~/.ssh/github-action
      - run: chmod 400 ~/.ssh/github-action
      - run: echo -e "Host vps\n\tUser root\n\tHostname ssh 91.108.110.231\n\tIdentityFile ~/.ssh/github-action\n\tStrictHostKeyChecking No" >> ~/.ssh/config
      - run: rsync -re ssh ./.next/ vps:/home/root/app-name/.next
      - run: ssh vps "pm2 restart portal"